### ISSUE TITLE
Is it possible to add a new TTS provider such as edge-tts?

### ISSUE THREAD

**Issue by zuojianghua** [pardeike/RimGPT#13]
Thank you for your excellent MOD

For some reason, I used Ollama to run llama3 at local
However, due to network conditions, Azure cannot be accessed in east asia.
Is it possible to add a new TTS provider such as edge tts?

Python has edge-tts library, but I don't know how to use it in C#

**Comment by pardeike** [comment]
So using local ollama isn’t enough?

**Comment by zuojianghua** [comment]
ollama work fine. but Azure tts doesn’t work in china

**Comment by pardeike** [comment]
Sorry, I was confused for a moment. The problem with solutions like edge tts is that they are not easy to install or use. There is no interface for C# and I will not support something that requires you to install python or other software that is not meant to be installed by ordinary users. It causes way too much support time that I don’t have. So for now this is a WONTFIX
