### ISSUE TITLE
Add support other TextToSpeech services

### ISSUE THREAD

**Issue by dmkenza** [pardeike/RimGPT#2]
Can you please add other TTS services.
I just cant register a free account for Azure.
My credit card doesn't work. 
I see a stupid message "Cardholder Name doesn't match the info on the card". 

Also other people had same, I see Microsoft ignores this problem.

https://learn.microsoft.com/en-us/answers/questions/375730/cardholder-name-doesnt-match-the-info-on-the-card?page=3#answers

**Comment by pardeike** [comment]
I don't know any other services that are good enough. Either super expensive or so bad quality that I rather rip out my ears.

**Comment by cseelhoff** [comment]
Just adding my two cents. Have you tried Tortoise-TTS or the "fast" fork? https://github.com/152334H/tortoise-tts-fast

By the way, @pardeike you always have the coolest ideas for coding projects ;-)

**Comment by pardeike** [comment]
@cseelhoff Regarding Tortoise: I only see a loose collection of things that need a lot of dependencies. Looks more like a lab project than a product. Not even sure how to make this into something that any random Rimworld player could use. Maybe I am missing something here but I am not even sure how to get this running on my own machine.

**Comment by dmkenza** [comment]
@pardeike 
Make please the window with comments be shown all time and won't hide.
I can't read on time.

**Comment by dmkenza** [comment]
I gave up and downloaded Visual Studio to start modding from zero. 
I spent half of a Sunday to figure out how to develop and run the mod.
I move the comment window to the top and add showing a previous message and the number.

I see there is a class SpeechSynthesizer exists for Windows for a robot voice. 
I use it in my fork, It's better than nothing. 
Unfortunately, Microsoft doesn't want to sell in Belarus. 

![Untitled](https://user-images.githubusercontent.com/66675746/234107851-d5a51a90-29e5-4d1c-b568-27598955f2a1.png)

**Comment by Neoony** [comment]
> I don't know any other services that are good enough. Either super expensive or so bad quality that I rather rip out my ears.

elevenlabs.ai
Probably the best you can get, but expensive
Usually its an option in such mods

**Comment by dicksensei69** [comment]
@dmkenza I looked through your github and couldn't find the fork.  I'd like to see how you were able to make the mods you listed.  I'm ok with the tts not working and having this mod pointed at my local Llama3 model but I can't get it to work with just text.  I can see it sending requests to the local server but nothing happens because I don't have azure set up. Any way ty for your input.
